"""Fidelity tests: the Python deal must match the original Java app card for card.

The fixture is generated by running ``tests/fixtures/Harness.java`` against the original
``Deck.java`` on a real JVM. Card identity depends on the deck's original array order,
so this catches ordering regressions that the RNG tests alone would not.
"""

from __future__ import annotations

import pathlib
from datetime import date, timedelta

import pytest

from app.data.loader import load_deck
from app.domain.cards import Orientation
from app.domain.deck import deal
from app.domain.reading import build_reading
from app.domain.seeding import LayeredSeed, NumerologySeed, Querent, compute_numerology
from app.domain.spreads import Position, Spread, get_spread

FIXTURE = pathlib.Path(__file__).parent / "fixtures" / "java_deal_golden.tsv"
DRAW_COUNT = 6

# Deliberate cleanups applied during extraction; the fixture holds the raw Java names.
RENAMED = {"Devil": "The Devil", "ACE of Coins": "Ace of Coins"}


def _fixture_rows() -> list[tuple[int, list[tuple[str, bool]]]]:
    rows = []
    for line in FIXTURE.read_text(encoding="utf-8").splitlines():
        parts = line.split("\t")
        seed = int(parts[0])
        draws = [
            (RENAMED.get(p.rsplit("|", 1)[0], p.rsplit("|", 1)[0]), p.rsplit("|", 1)[1] == "true")
            for p in parts[1:]
        ]
        rows.append((seed, draws))
    assert rows, "fixture is empty"
    return rows


def _probe_spread(size: int) -> Spread:
    """A synthetic spread used only to pull a known number of cards."""
    positions = tuple(
        Position(key=f"p{i}", title=f"P{i}", prompt="", accent="ember") for i in range(size)
    )
    return Spread(slug="probe", name="Probe", tagline="", description="", positions=positions)


@pytest.mark.parametrize("seed,expected", _fixture_rows())
def test_deal_matches_original_java(seed: int, expected: list[tuple[str, bool]]) -> None:
    drawn = deal(load_deck(), _probe_spread(DRAW_COUNT), seed)
    got = [(d.card.name, d.is_reversed) for d in drawn]
    assert got == expected


def test_deck_is_ordered_by_source_index() -> None:
    cards = load_deck().cards
    assert [c.source_index for c in cards] == list(range(78))
    # The original array began with these; display order would start differently.
    assert [c.name for c in cards[:3]] == ["The Fool", "The Emperor", "Strength"]


def test_numerology_matches_original_formula() -> None:
    """Worked example: name of 6 chars, age 33, Male (choice 1), day 217."""
    querent = Querent(name="Gentry", age=33, resonance="Male")
    numerology = compute_numerology(querent, date(2026, 8, 5))

    assert numerology.name_value == 7  # int(1.5 + 6)
    assert numerology.age_value == 107  # 7 + 100
    assert numerology.resonance_value == 115  # 107 + 7 + 1
    assert numerology.day_of_year == 217
    assert numerology.seed == (7 + 107 + 115 + 217) // 33


def test_same_querent_same_day_is_stable() -> None:
    """The original's core promise: one reading per person per day."""
    deck, strategy, on = load_deck(), NumerologySeed(), date(2026, 8, 5)
    spread = _probe_spread(3)
    querent = Querent(name="Ada", age=29, resonance="Female")

    first = build_reading(deck, spread, querent, strategy, on)
    second = build_reading(deck, spread, querent, strategy, on)
    assert first.seed == second.seed
    assert [d.card.slug for d in first.drawn] == [d.card.slug for d in second.drawn]


def test_seed_advances_after_an_age_interval() -> None:
    """Documenting a quirk of the original formula.

    Seed = (total) // age, so readings stay the same until ``day_of_year`` advances far
    enough to bump the integer quotient. For age 29 the seed holds for a 29-day window
    before changing. This is faithful to the original; :class:`DailySeed` is the fix.
    """
    strategy, on = NumerologySeed(), date(2026, 1, 1)
    querent = Querent(name="Ada", age=29, resonance="Female")

    same_day = build_reading(load_deck(), _probe_spread(1), querent, strategy, on)
    next_day = build_reading(load_deck(), _probe_spread(1), querent, strategy, on.replace(day=2))
    assert same_day.seed == next_day.seed, "consecutive days SHOULD collide; the formula is "// \
        "total // age"

    advanced = build_reading(
        load_deck(), _probe_spread(1), querent, strategy, on.replace(day=2 + 29)
    )
    assert advanced.seed != same_day.seed, "after one age-window the seed must advance"


def test_daily_seed_differs_every_day_of_the_year() -> None:
    """DailySeed is the user-facing fix: every day yields a different reading."""
    
    strategy = LayeredSeed()
    querent = Querent(name="Ada", age=29, resonance="Female")
    seeds = {
        strategy.seed(querent, date(2026, 1, 1) + timedelta(days=offset), "hear-help-hold")
        for offset in range(365)
    }
    assert len(seeds) == 365, "DailySeed collapsed at least one day-of-year"


def test_daily_seed_is_stable_for_the_same_querent_same_day() -> None:
    
    strategy, querent = LayeredSeed(), Querent(name="Ada", age=29, resonance="Female")
    on, spread = date(2026, 8, 5), "hear-help-hold"
    assert strategy.seed(querent, on, spread) == strategy.seed(querent, on, spread)


def test_different_spreads_produce_different_cards() -> None:
    """Regression: Hear/Help/Hold and Past/Present/Future must not return the same
    cards. The seed is salted with the spread slug, so the same querent on the same
    day gets a different reading for each spread.
    """
    
    deck, strategy, querent, on = load_deck(), LayeredSeed(), Querent(name="Ada", age=29, resonance="Female"), date(2026, 8, 5)
    a = build_reading(deck, get_spread("hear-help-hold"), querent, strategy, on)
    b = build_reading(deck, get_spread("past-present-future"), querent, strategy, on)
    assert [d.card.slug for d in a.drawn] != [d.card.slug for d in b.drawn], (
        "Different spreads produced the same cards — the spread slug is not salted into the seed."
    )


def test_numerology_seed_is_spread_agnostic() -> None:
    """The faithful mode is bit-exact to the original Java: one spread, one reading.
    Different spreads MUST produce the same cards under NumerologySeed so the
    'faithful 1997' promise is preserved.
    """
    from app.domain.seeding import NumerologySeed

    deck, strategy, querent, on = load_deck(), NumerologySeed(), Querent(name="Ada", age=29, resonance="Female"), date(2026, 8, 5)
    a = build_reading(deck, get_spread("hear-help-hold"), querent, strategy, on)
    b = build_reading(deck, get_spread("past-present-future"), querent, strategy, on)
    assert [d.card.slug for d in a.drawn] == [d.card.slug for d in b.drawn], (
        "NumerologySeed must reproduce the original single-spread behaviour"
    )


def test_reversed_cards_render_reversed_text() -> None:
    """The original bug: every card's reversed text was an empty string."""
    for card in load_deck().cards:
        assert card.reversed.summary.strip()
        assert card.reversed.body
        assert card.face(Orientation.REVERSED) is card.reversed
        assert card.face(Orientation.UPRIGHT) is card.upright
