"""Verify the JavaRandom port against fixtures generated by a real JVM.

The fixture file is produced by ``tests/fixtures/Golden.java``, so these tests prove the
Python port is bit-exact rather than merely plausible.
"""

from __future__ import annotations

import pathlib

import pytest

from app.domain.java_random import JavaRandom, java_shuffle

FIXTURE = pathlib.Path(__file__).parent / "fixtures" / "java_random_golden.tsv"


def _load(kind: str) -> list[list[str]]:
    rows = []
    for line in FIXTURE.read_text(encoding="utf-8").splitlines():
        parts = line.split("\t")
        if parts and parts[0] == kind:
            rows.append(parts[1:])
    assert rows, f"no {kind} rows found in fixture"
    return rows


@pytest.mark.parametrize("row", _load("RAW"))
def test_raw_streams_match_java(row: list[str]) -> None:
    seed, int_csv, double_csv = int(row[0]), row[1], row[2]

    rng = JavaRandom(seed)
    got_ints = [rng.next_int() for _ in range(5)]
    assert got_ints == [int(v) for v in int_csv.split(",")]

    rng = JavaRandom(seed)
    got_doubles = [rng.next_double() for _ in range(3)]
    assert got_doubles == [float(v) for v in double_csv.split(",")]


@pytest.mark.parametrize("row", _load("BOUND"))
def test_bounded_next_int_matches_java(row: list[str]) -> None:
    seed, bound, expected_csv = int(row[0]), int(row[1]), row[2]
    rng = JavaRandom(seed)
    got = [rng.next_int(bound) for _ in range(6)]
    assert got == [int(v) for v in expected_csv.split(",")]


@pytest.mark.parametrize("row", _load("DECK"))
def test_deck_shuffle_and_reversals_match_java(row: list[str]) -> None:
    """Mirrors Deck.java: shuffle 78 cards, then one nextDouble() per draw."""
    seed, order_csv, reversed_csv = int(row[0]), row[1], row[2]

    rng = JavaRandom(seed)
    deck = list(range(78))
    java_shuffle(deck, rng)
    assert deck == [int(v) for v in order_csv.split(",")]

    got = [rng.next_double() > 0.5 for _ in range(10)]
    assert got == [v == "true" for v in reversed_csv.split(",")]


def test_next_int_rejects_non_positive_bound() -> None:
    rng = JavaRandom(1)
    with pytest.raises(ValueError):
        rng.next_int(0)
    with pytest.raises(ValueError):
        rng.next_int(-3)
